name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v6
          
        - name: List, read, echo
          run: |
            echo "Hello to my new workflow"
            ls -ltra
            cat README.md
        
        - name: ASCII content cowsay
          run: cowsay -f bee "bzzZZz BZZzzZZ Bzzz flower" >> bee.txt

        # - name: List files
        #   run: ls

        # - name: Read files
        #   run: cat README.md
